export const SEARCH = "SEARCH";
export const GET_COMPANY_PROFILE = "GET_COMPANY_PROFILE";
export const SET_CDD_QUESTIONNAIRE = "SET_CDD_QUESTIONNAIRE"
export const SET_CDD_QUESTION_ANSWER = "SET_CDD_QUESTION_ANSWER"
